apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-brain-backend
  namespace: ai-brain-vault
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-brain-backend
  template:
    metadata:
      labels:
        app: ai-brain-backend
    spec:
      containers:
      - name: backend
        image: ai-brain-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: secret-access-key
        - name: AWS_REGION
          value: "us-east-1"
        - name: S3_BUCKET
          value: "ai-brain-vault-audio"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: XAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: xai-secret
              key: api-key
        - name: AUTH0_DOMAIN
          valueFrom:
            secretKeyRef:
              name: auth0-secret
              key: domain
        - name: AUTH0_AUDIENCE
          valueFrom:
            secretKeyRef:
              name: auth0-secret
              key: audience
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ai-brain-backend
  namespace: ai-brain-vault
spec:
  selector:
    app: ai-brain-backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ai-brain-backend-hpa
  namespace: ai-brain-vault
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai-brain-backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 