apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-brain-frontend
  namespace: ai-brain-vault
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-brain-frontend
  template:
    metadata:
      labels:
        app: ai-brain-frontend
    spec:
      containers:
      - name: frontend
        image: ai-brain-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: BACKEND_URL
          value: "http://ai-brain-backend:8000"
        - name: AUTH0_SECRET
          valueFrom:
            secretKeyRef:
              name: auth0-secret
              key: secret
        - name: AUTH0_ISSUER_BASE_URL
          valueFrom:
            secretKeyRef:
              name: auth0-secret
              key: issuer-base-url
        - name: AUTH0_BASE_URL
          value: "https://ai-brain-vault.com"
        - name: AUTH0_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: auth0-secret
              key: client-id
        - name: AUTH0_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth0-secret
              key: client-secret
        - name: AUTH0_AUDIENCE
          valueFrom:
            secretKeyRef:
              name: auth0-secret
              key: audience
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ai-brain-frontend
  namespace: ai-brain-vault
spec:
  selector:
    app: ai-brain-frontend
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ai-brain-frontend-hpa
  namespace: ai-brain-vault
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai-brain-frontend
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 